# Generated by Django 3.1.3 on 2021-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Order_form',
                'verbose_name_plural': 'Order_forms',
            },
        ),
    ]
